"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import PremiumApp from "./premium";

type Route = "landing"|"dashboard"|"monitor"|"timeline"|"network"|"investigation"|"evidence"|"sources";
type Post = {id:string; platform:string; author:string; time:string; text:string; likes:number; shares:number; risk:number; sentiment:string};
const basePosts:Post[] = [
 {id:"POST-00421",platform:"X",author:"@citywatch_24",time:"09:12:08",text:"Something feels wrong with the water supply this morning. Has anyone else noticed?",likes:184,shares:47,risk:54,sentiment:"Concerned"},
 {id:"POST-00432",platform:"Telegram",author:"@city_alert",time:"09:26:14",text:"URGENT: reports are spreading about contamination in the city water supply. Verify before sharing.",likes:421,shares:87,risk:84,sentiment:"Negative"},
 {id:"POST-00446",platform:"X",author:"@BhopalPulse",time:"09:41:22",text:"Authorities are hiding the truth about contaminated water, according to circulating posts.",likes:932,shares:286,risk:87,sentiment:"Negative"},
 {id:"POST-00459",platform:"Instagram",author:"@localupdates",time:"10:03:19",text:"Community update: unverified claims regarding water quality are spreading. Stay informed.",likes:611,shares:128,risk:68,sentiment:"Fear"},
 {id:"POST-00473",platform:"Telegram",author:"@alert_channel",time:"10:27:02",text:"Share this before it gets deleted — alleged water contamination reported across districts.",likes:1802,shares:615,risk:91,sentiment:"High emotion"},
 {id:"POST-00488",platform:"X",author:"@civic_signal",time:"11:04:31",text:"Water supply conversation now exceeds 10K engagements. Original claims remain unverified.",likes:3412,shares:1124,risk:82,sentiment:"Negative"},
 {id:"POST-00501",platform:"Facebook",author:"City Community Forum",time:"11:32:04",text:"Discussion: Has anyone received official guidance about the water supply rumours?",likes:728,shares:94,risk:61,sentiment:"Concerned"},
 {id:"POST-00524",platform:"X",author:"@newswire_india",time:"12:15:18",text:"Pattern alert: near-identical water narrative posts observed in a short time window.",likes:921,shares:402,risk:89,sentiment:"Negative"},
];
// Deterministic local corpus (48 posts) used by the prototype; the timeline highlights the key eight events.
const posts:Post[] = [...basePosts,...Array.from({length:40},(_,i)=>({id:"POST-"+String(530+i).padStart(5,"0"),platform:["X","Telegram","Instagram","Facebook"][i%4],author:["@city_signal","@community_watch","@civicdesk","@localbrief"][i%4],time:String(12+Math.floor(i/12)).padStart(2,"0")+":"+String((i*7)%60).padStart(2,"0")+":15",text:["Residents discuss unverified water-quality claims circulating online.","Community members request official clarification on the water narrative.","Monitoring note: similar water-supply language appears across public posts.","Local discussion references the fictional contamination narrative."][i%4],likes:80+i*19,shares:12+i*7,risk:42+(i%8)*5,sentiment:i%3===0?"Concerned":"Negative"}))];
const nav = [{id:"dashboard",icon:"▦",name:"Overview"},{id:"monitor",icon:"◉",name:"Live Monitor"},{id:"timeline",icon:"◷",name:"Timeline"},{id:"network",icon:"⌘",name:"Network Analysis"},{id:"investigation",icon:"✦",name:"AI Investigation"},{id:"evidence",icon:"◈",name:"Evidence"},{id:"sources",icon:"⊞",name:"Data Sources"}];
const narratives=[["Contaminated Water Supply","HIGH","87%"],["Fuel Shortage Rumours","MEDIUM","64%"],["Campus Security Alert","LOW","31%"],["Fake Government Notice","HIGH","81%"]];
function Badge({children,kind=""}:{children:React.ReactNode;kind?:string}){return <span className={"badge "+kind}>{children}</span>}
function Header(){return <header className="top"><div><b>SOCIAL PULSE</b><span> INTELLIGENCE CENTER</span></div><div className="topright"><Badge kind="live">● LIVE ANALYSIS</Badge><span className="investigation">Current investigation: <b>Water Contamination Narrative</b></span></div></header>}
function Sidebar({route}:{route:Route}){return <aside className="side"><Link href="/" className="brand"><i>◈</i><strong>SOCIAL PULSE</strong><small>AI SOCIAL INTELLIGENCE</small></Link><nav>{nav.map(n=><Link key={n.id} className={route===n.id?"active":""} href={"/"+n.id}><i>{n.icon}</i>{n.name}</Link>)}</nav><div className="systems"><p>SYSTEM STATUS</p><b className="online">● Operational</b><p>CONNECTED SOURCES</p>{["X             ●","Telegram      ●","Instagram     ◐","Facebook      ◐"].map(x=><span key={x}>{x}</span>)}</div></aside>}
function Shell({route,children}:{route:Route;children:React.ReactNode}){return <div className="shell"><Sidebar route={route}/><main className="main"><Header/>{children}</main></div>}
const Title=({title,sub}:{title:string;sub:string})=><div className="title"><h1>{title}</h1><p>{sub}</p></div>;
function ActivityChart(){const points="0,164 50,155 100,160 150,145 200,138 250,102 300,40 350,72 400,89 450,115 500,128 550,136 600,142";return <div className="chart"><div className="axis">Posts / Activity</div><svg viewBox="0 0 600 190" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#20c5e6" stopOpacity=".4"/><stop offset="1" stopColor="#20c5e6" stopOpacity="0"/></linearGradient></defs><path d={"M0,190 L"+points+" L600,190 Z"} fill="url(#g)"/><polyline points={points} fill="none" stroke="#3dd5f4" strokeWidth="3"/><line x1="0" y1="125" x2="600" y2="125" className="grid"/><line x1="0" y1="65" x2="600" y2="65" className="grid"/></svg><div className="times">{["08:00","09:00","10:00","11:00","12:00","13:00","14:00"].map(t=><span key={t}>{t}</span>)}</div></div>}
function Dashboard(){return <Shell route="dashboard"><section className="page"><div className="row"><Title title="SOCIAL INTELLIGENCE COMMAND CENTER" sub="Real-time narrative monitoring and cross-platform analysis"/><Link className="button" href="/investigation">LOAD DEMO INVESTIGATION</Link></div><div className="kpis">{[["POSTS ANALYZED","12,486","+18.4%"],["ACTIVE NARRATIVES","17","+4 today"],["HIGH-RISK NARRATIVES","04",""],["COORDINATED CLUSTERS","08",""],["PLATFORMS","4",""]].map(x=><div className="card kpi" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><em>{x[2]}</em></div>)}</div><div className="grid2"><div className="card risk"><div><small>NARRATIVE RISK</small><h2>Contaminated Water Supply</h2><p>AI indicator based on observed spread and activity patterns.</p></div><div className="score">87<sup>%</sup><Badge kind="high">HIGH RISK</Badge></div><div className="metrics">{[["Velocity","+340%"],["Cross-platform","4"],["Coordination","78%"],["Negative","91%"]].map(x=><span key={x[0]}>{x[0]}<b>{x[1]}</b></span>)}</div></div><div className="card detection"><small>AI DETECTION ALERT</small><h3>Potential coordinated narrative detected.</h3><div className="confidence">Confidence <b>92%</b><div><i style={{width:"92%"}}/></div></div><ul><li>Similar wording</li><li>Synchronized posting</li><li>Shared URLs</li><li>Cross-platform propagation</li></ul><Link href="/investigation">INVESTIGATE NARRATIVE →</Link></div></div><div className="gridWide"><div className="card"><small>NARRATIVE ACTIVITY</small><ActivityChart/></div><div className="card distribution"><small>PLATFORM DISTRIBUTION</small>{[["X",45],["Telegram",31],["Instagram",14],["Facebook",10]].map(x=><div key={x[0]}><span>{x[0]}</span><i><b style={{width:x[1]+"%"}}/></i><em>{x[1]}%</em></div>)}</div></div><div className="card narratives"><small>EMERGING NARRATIVES</small>{narratives.map((n,i)=><Link href="/investigation" key={n[0]}><b>0{i+1}</b><span>{n[0]}</span><Badge kind={n[1].toLowerCase()}>{n[1]}</Badge><em>{n[2]}</em></Link>)}</div></section></Shell>}
function Monitor(){const [filter,setFilter]=useState("All"),[query,setQuery]=useState(""),[live,setLive]=useState(false),[visible,setVisible]=useState(5);useEffect(()=>{if(!live)return;const t=setInterval(()=>setVisible(x=>Math.min(posts.length,x+1)),2200);return()=>clearInterval(t)},[live]);const list=posts.slice(0,visible).filter(p=>(filter==="All"||p.platform===filter)&&(p.author+" "+p.text).toLowerCase().includes(query.toLowerCase()));return <Shell route="monitor"><section className="page"><div className="row"><Title title="LIVE MONITOR" sub="Continuously ingesting and classifying prototype social signals."/><button className={"toggle "+(live?"on":"")} onClick={()=>setLive(!live)}>● {live?"STREAM ACTIVE":"LIVE SIMULATION"}</button></div><div className="filters">{["All","X","Telegram","Instagram","Facebook"].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?"selected":""}>{x}</button>)}<input placeholder="Search posts..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="stream">{list.map(p=><article className="post card" key={p.id}><div className="platform">{p.platform==="Telegram"?"✈":p.platform==="Instagram"?"◎":p.platform==="Facebook"?"f":"𝕏"}</div><div className="postbody"><b>{p.author}</b><time>08 Sep 2026 • {p.time}</time><p>{p.text}</p><span>↗ {(p.likes+p.shares).toLocaleString()} engagements</span></div><div className="postrisk"><Badge kind={p.risk>80?"high":p.risk>60?"medium":"low"}>{p.sentiment}</Badge><strong>Risk {p.risk}%</strong></div></article>)}</div>{!list.length&&<div className="empty">No posts match the current filters.</div>}</section></Shell>}
function Timeline(){const [selected,setSelected]=useState(posts[0]);return <Shell route="timeline"><section className="page"><Title title="NARRATIVE TIMELINE" sub="Reconstruct how a conversation evolved across platforms."/><div className="timeline-layout"><div className="timeline card">{posts.map(p=><button onClick={()=>setSelected(p)} className={selected.id===p.id?"event active":"event"} key={p.id}><time>{p.time.slice(0,5)}</time><i>{p.platform}</i><span>{p.text}</span></button>)}</div><aside className="detail card"><small>EVENT DETAIL</small><Badge>{selected.platform}</Badge><h3>{selected.author}</h3><time>08 Sep 2026 • {selected.time}</time><p>{selected.text}</p><hr/><div>Engagement <b>{(selected.likes+selected.shares).toLocaleString()}</b></div><div>Sentiment <b>{selected.sentiment}</b></div><div>Risk <b className="danger">{selected.risk}%</b></div><small>NARRATIVE VELOCITY</small><ActivityChart/></aside></div></section></Shell>}
function Network(){const nodes=[[50,50],[110,25],[165,70],[95,110],[210,125],[270,65],[310,120],[360,35],[400,105],[465,65],[530,125],[585,40],[615,110],[680,72],[735,122],[760,35]];return <Shell route="network"><section className="page"><Title title="COORDINATION NETWORK" sub="Identify relationships between accounts, posts and narratives."/><div className="network-layout"><div className="card graph"><svg viewBox="0 0 800 260">{nodes.slice(1).map((n,i)=><line key={i} x1={nodes[i][0]} y1={nodes[i][1]} x2={n[0]} y2={n[1]} className={i>3&&i<10?"hotline":"edge"}/>)}{nodes.map((n,i)=><g key={i}><circle cx={n[0]} cy={n[1]} r={i===6?20:i%3===0?13:9} className={i===6?"central":i%2?"account":"postnode"}/><text x={n[0]} y={n[1]+4} textAnchor="middle">{i===6?"N":"•"}</text></g>)}</svg><div className="legend">● Accounts &nbsp; ● Posts &nbsp; ● Narrative &nbsp; — Shared URL / synchronization</div></div><aside className="card analysis"><small>COORDINATION DETECTED</small><div className="prob">89<sup>%</sup></div>{[["Cluster size","18 accounts"],["Content similarity","87%"],["Time synchronization","92%"],["Shared URLs","14"]].map(x=><p key={x[0]}>{x[0]} <b>{x[1]}</b></p>)}<hr/><small>AI INTERPRETATION</small><p>Several accounts exhibit highly similar content and synchronized posting behavior. These indicators are consistent with potential coordinated amplification.</p><Link className="button" href="/investigation">INVESTIGATE</Link></aside></div></section></Shell>}
function Investigation(){const [answer,setAnswer]=useState("Select a question to receive an evidence-aware AI assessment.");const replies:Record<string,string>={"Why is this narrative high risk?":"The 87% prototype risk score is driven by a +340% activity velocity, four-platform propagation, and elevated negative/emotional language. This is a risk indicator, not confirmation of the claim.","How did the narrative spread?":"The timeline indicates an initial X post at 09:12, followed by Telegram amplification at 09:26, then Instagram and Facebook distribution. Engagement increased sharply after the 10:27 Telegram message.","Which accounts appear coordinated?":"A cluster of 18 accounts shows closely timed, highly similar posts and 14 shared URLs. The pattern warrants human review; it does not establish intent or attribution.","What evidence supports the risk score?":"Observed evidence includes post timestamps, engagement metadata, content-similarity signals and cross-platform recurrence. Assessment confidence is 92%, and human verification is required."};return <Shell route="investigation"><section className="page"><Title title="AI INVESTIGATION" sub={'Selected narrative: “Contaminated Water Supply”'}/><div className="summary card"><small>AI INVESTIGATION SUMMARY</small><h2>A rapidly spreading narrative regarding alleged water contamination was detected across multiple platforms.</h2><p>Activity increased sharply within a three-hour period and similar content appeared across multiple accounts. This fictional demonstration scenario requires human verification.</p><div>{[["RISK SCORE","87%"],["AI CONFIDENCE","92%"],["CROSS-PLATFORM SPREAD","4 platforms"],["COORDINATION SCORE","78%"]].map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}</div></div><div className="findings card"><small>AI FINDINGS</small>{["Narrative acceleration","Cross-platform propagation","Potential coordinated activity","High emotional intensity"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span><Badge kind={i===2?"medium":"high"}>{i===2?"MEDIUM-HIGH":"HIGH"} CONFIDENCE</Badge></div>)}</div><div className="ask card"><small>ASK AI</small><h3>Evidence-aware investigation assistant</h3><div className="questions">{Object.keys(replies).map(q=><button key={q} onClick={()=>setAnswer(replies[q])}>{q}</button>)}</div><div className="response"><Badge>AI ASSESSMENT</Badge><p>{answer}</p><small>Assessment based on observed activity patterns and available evidence. Human verification is recommended.</small></div></div><footer>AI-generated assessment. Human verification required before operational action.</footer></section></Shell>}
function Evidence(){const [state,setState]=useState("VERIFY EVIDENCE");const run=()=>{setState("CHECKING HASH...");setTimeout(()=>setState("VERIFYING TIMESTAMP..."),650);setTimeout(()=>setState("✓ EVIDENCE VERIFIED"),1350)};return <Shell route="evidence"><section className="page"><Title title="EVIDENCE INTEGRITY" sub="Preserve and verify captured digital evidence."/><div className="evidence-top"><div className="card ledger"><small>PROTOTYPE EVIDENCE LEDGER</small><div className="chain"><b>CAPTURE</b><i>↓</i><b>SHA-256 HASH</b><i>↓</i><b>TIMESTAMP</b><i>↓</i><b>IMMUTABLE RECORD</b><i>↓</i><b>VERIFICATION</b></div><button className="button" onClick={run}>{state}</button>{state.includes("✓")&&<p className="verified">✓ HASH VERIFIED &nbsp; ✓ TIMESTAMP VERIFIED &nbsp; ✓ EVIDENCE UNCHANGED</p>}</div><div className="card evidence-note">Prototype implementation demonstrates cryptographic evidence integrity using SHA-256 hashing. A production deployment can anchor evidence hashes to a permissioned blockchain.</div></div><div className="evidence-grid">{["Telegram","X","Instagram","Facebook"].map((x,i)=><article className="card" key={x}><small>EVIDENCE #00482{i+1}</small><h3>{x}</h3><p>Captured<br/><b>08 Sep 2026 • 11:{42+i}:09</b></p><p>Content hash<br/><code>a8f92c7d...91be</code></p><Badge kind="verified">✓ VERIFIED</Badge></article>)}</div></section></Shell>}
function Sources(){return <Shell route="sources"><section className="page"><Title title="DATA SOURCES" sub="Prototype source health and ingestion pipeline."/><div className="source-grid">{[["𝕏","X","CONNECTED","8,421 posts"],["✈","Telegram","CONNECTED","3,217 messages"],["◎","Instagram","PROTOTYPE","Simulated stream"],["f","Facebook","PROTOTYPE","Simulated stream"]].map(x=><div className="card source" key={x[1]}><i>{x[0]}</i><h2>{x[1]}</h2><Badge kind={x[2]==="CONNECTED"?"verified":"medium"}>{x[2]}</Badge><p>{x[3]}</p></div>)}</div><div className="pipeline card"><div><b>X</b><b>Telegram</b><b>Instagram</b><b>Facebook</b></div><i>→</i><div><strong>INGESTION</strong><i>↓</i><strong>NORMALIZATION</strong><i>↓</i><strong>HISTORICAL STORAGE</strong><i>↓</i><strong>AI ANALYSIS</strong><i>↓</i><strong>INTELLIGENCE</strong></div></div><footer>Connected sources show prototype-ready integrations. Instagram and Facebook are clearly simulated for this demonstration.</footer></section></Shell>}
function Landing(){return <div className="landing"><div className="landnav"><span>◈ SOCIAL PULSE <small>AI SOCIAL INTELLIGENCE</small></span><Link href="/dashboard">INTELLIGENCE CENTER →</Link></div><section><Badge kind="live">● SYSTEM OPERATIONAL</Badge><h1>DETECT.<br/><em>TRACE.</em><br/>UNDERSTAND.</h1><p>AI-powered social intelligence for detecting emerging narratives, tracing cross-platform propagation and identifying coordinated activity.</p><div><Link className="button" href="/investigation">LAUNCH INVESTIGATION</Link><Link className="ghost" href="/dashboard">VIEW INTELLIGENCE CENTER</Link></div></section><div className="capabilities">{[["DETECT","Identify emerging narratives and suspicious activity."],["TRACE","Reconstruct conversations across platforms and time."],["EXPLAIN","Generate AI-assisted, evidence-backed investigation insights."]].map(x=><article key={x[0]}><i>✦</i><b>{x[0]}</b><p>{x[1]}</p></article>)}</div><div className="platforms">MONITORED PROTOTYPE SOURCES　 <b>𝕏</b> X　 <b>✈</b> TELEGRAM　 <b>◎</b> INSTAGRAM　 <b>f</b> FACEBOOK</div></div>}
export default function IntelligenceApp({route}:{route:Route}){return <PremiumApp route={route}/>}
